### PR TITLE
Add Support for Recursive Pact File Globbing

### PR DESCRIPTION
**Pull request by maksimt**
Implements #104

### CODE REVIEW

**Comment by maksimt** [comment]
Ping @r1chardj0n3s for visibility.

**Comment by maksimt** [comment]
Bump. Is anyone with merge permissions around?

**Comment by r1chardj0n3s** [comment]
Hi, I've been very busy elsewhere. This patch looks good to me though, thanks for persisting.

**Comment by r1chardj0n3s** [comment]
Just need to look into that CI failure.

**Comment by maksimt** [comment]
Ah looks like you just fixed the CI failure (I fixed it too before realizing you fixed it, lol). Rebased, let's see if the CI is happy now.

**Pull request merged**
